"""add scheduler task runs

Revision ID: 14c67e743eec
Revises: a36c42a0dca5
Create Date: 2026-06-15 18:22:45.332509

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '14c67e743eec'
down_revision: Union[str, Sequence[str], None] = 'a36c42a0dca5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scheduler_task_runs',
    sa.Column('function_path', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=False),
    sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('function_path')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scheduler_task_runs')
    # ### end Alembic commands ###
