"""add verification codes

Revision ID: a36c42a0dca5
Revises: d5857fc42b2e
Create Date: 2026-06-11 10:32:24.806066

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a36c42a0dca5'
down_revision: Union[str, Sequence[str], None] = 'd5857fc42b2e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('registration', 'password_recovery', name='verificationpurpose').create(op.get_bind())
    op.create_table('verification_codes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('purpose', postgresql.ENUM('registration', 'password_recovery', name='verificationpurpose', create_type=False), nullable=False),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(length=6), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('valid_until', sa.DateTime(timezone=True), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_verification_codes_email'), 'verification_codes', ['email'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_verification_codes_email'), table_name='verification_codes')
    op.drop_table('verification_codes')
    sa.Enum('registration', 'password_recovery', name='verificationpurpose').drop(op.get_bind())
    # ### end Alembic commands ###
