"""users status postgres enum

Revision ID: e62aef1f5da8
Revises: g5b2c9e3a1d2
Create Date: 2026-04-24 09:20:55.480622

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e62aef1f5da8"
down_revision: str | Sequence[str] | None = "g5b2c9e3a1d2"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

_userstatus = sa.Enum("active", "inactive", "disabled", name="userstatus")


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    _userstatus.create(op.get_bind())
    # --- additional migration code ---
    # Postgres cannot cast a VARCHAR column default to ENUM in one ALTER.
    op.execute(sa.text("ALTER TABLE users ALTER COLUMN status DROP DEFAULT"))
    op.alter_column(
        "users",
        "status",
        existing_type=sa.VARCHAR(length=8),
        type_=sa.Enum(
            "active",
            "inactive",
            "disabled",
            name="userstatus",
            create_type=False,
        ),
        existing_nullable=False,
        postgresql_using="status::userstatus",
    )
    op.execute(
        sa.text("ALTER TABLE users ALTER COLUMN status SET DEFAULT 'active'::userstatus"),
    )
    op.execute(sa.text("ALTER TABLE users DROP CONSTRAINT IF EXISTS userstatus"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(sa.text("ALTER TABLE users ALTER COLUMN status DROP DEFAULT"))
    op.alter_column(
        "users",
        "status",
        existing_type=sa.Enum(
            "active",
            "inactive",
            "disabled",
            name="userstatus",
            create_type=False,
        ),
        type_=sa.VARCHAR(length=8),
        existing_nullable=False,
        postgresql_using="status::text",
    )
    op.execute(
        sa.text("ALTER TABLE users ALTER COLUMN status SET DEFAULT 'active'::character varying"),
    )
    _userstatus.drop(op.get_bind())
    op.execute(sa.text("ALTER TABLE users DROP CONSTRAINT IF EXISTS userstatus"))
    op.create_check_constraint(
        "userstatus",
        "users",
        "status IN ('active', 'inactive', 'disabled')",
    )
    # ### end Alembic commands ###
